---
title: "ISA401 Final Project Doc"
author: "Team 10"
date: "2026-05-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Source 1: Census ACS Income (25-44)

# Sydney
```{r}
library(tidycensus)
library(tidyverse)

# Load the list of all available variables for 2024
v24 <- load_variables(2024, "acs1", cache = TRUE)

# Use RStudio's View to search keywords like "age", "income", or "rent"
View(v24)
Sys.getenv("CENSUS_API_KEY")

income_vars <- c(income_25_through_44 = "B19049_003")

income_2010 <- get_acs(geography = "state", variables = income_vars, year = 2010, survey = "acs1")
income_2010$year <- 2010

income_2024 <- get_acs(geography = "state", variables = income_vars, year = 2024, survey = "acs1")
income_2024$year <- 2024

income_combined <- rbind(income_2010, income_2024)
income_final <- pivot_wider(income_combined, id_cols = NAME, names_from = year, names_prefix = "income_", values_from = estimate)
```


## Source 2: Census ACS Rent Data (25-44)

# Sydney
```{r}
rent_vars = c(median_rent ="B25064_001")
rent_2010 <- get_acs(geography = "state", variables = rent_vars, year = 2010, survey = "acs1")
rent_2010$year <- 2010
rent_2024 <- get_acs(geography = "state", variables = rent_vars, year = 2024, survey = "acs1")
rent_2024$year <- 2024

rent_combined <- rbind(rent_2010, rent_2024)

rent_final <- pivot_wider(rent_combined, id_cols = NAME, names_from = year, names_prefix = "rent_", values_from = estimate)
```

## Source 3: FRED CPI Data

# Annie
# Annie
ux
```{r}
install.packages("tidyquant")
```

```{r}
library(tidyverse)
library(tidyquant)
library(lubridate)

# Pull CPI data from FRED
# CPIAUCSL = Consumer Price Index for All Urban Consumers
cpi_data <- tq_get("CPIAUCSL",
                   get = "economic.data",
                   from = "2010-01-01",
                   to = "2024-12-31")

# Keep only 2010 and 2024, then calculate average CPI for each year
cpi_final <- cpi_data %>%
  mutate(year = year(date)) %>%
  filter(year %in% c(2010, 2024)) %>%
  group_by(year) %>%
  summarize(avg_cpi = mean(price, na.rm = TRUE)) %>%
  pivot_wider(names_from = year,
              names_prefix = "cpi_",
              values_from = avg_cpi)

cpi_final

# Create inflation factor to adjust 2010 dollars into 2024 dollars
inflation_factor <- cpi_final$cpi_2024 / cpi_final$cpi_2010

inflation_factor
```


The CPI data from FRED was used to calculate an inflation adjustment factor of 1.43848. This means 2010 dollar values can be multiplied by 1.43848 to compare them fairly with 2024 dollar values.



## Source 4: BLS OES Wage/Employment Data

# Cam

