---
title: "ISA401 Proj"
author: "Sydney Booth"
date: "2026-05-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidycensus)
library(tidyverse)

# Load the list of all available variables for 2024
v24 <- load_variables(2024, "acs1", cache = TRUE)

# Use RStudio's View to search keywords like "age", "income", or "rent"
View(v24)
Sys.getenv("CENSUS_API_KEY")
```

```{r}
vars <- c(income_25_through_44 = "B19049_003", rent = "B25064_001")
acs_2010 <- get_acs(
  geography = "state", 
  variables = vars, 
  year = 2010, 
  survey = "acs1"
) |> mutate(vintage = 2010)  |>
rename(
    avg_salary = estimate,
    plus_minus = moe, 
    year = vintage
  )
```
```{r}
acs_2024 <- get_acs(
  geography = "state", 
  variables = vars, 
  year = 2024, 
  survey = "acs1"
) |> mutate(vintage = 2024) |>
rename(
    avg_salary = estimate,
    plus_minus = moe, 
    year = vintage
  )
```
```{r}
acs_2010_tidy <- acs_2010 |>
  select(GEOID, NAME, variable, avg_salary) |>
  pivot_wider(names_from = variable, values_from = avg_salary)

# 2. Clean the 2024 data so each state is 1 row
acs_2024_tidy <- acs_2024 |>
  select(GEOID, NAME, variable, avg_salary) |>
  pivot_wider(names_from = variable, values_from = avg_salary)

# 3. Now join them - they will match up perfectly
comparison_table <- inner_join(
  acs_2010_tidy, 
  acs_2024_tidy, 
  by = c("GEOID", "NAME"), 
  suffix = c("_2010", "_2024")
)
```

